<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Recuperar contraseña · Yeral Stecti</title>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:wght@600;700&display=swap" rel="stylesheet">
    <style>
        :root{--pink:#dc4f87;--ink:#332d35;--muted:#817780;--line:#f0e6ea}*{box-sizing:border-box}body{min-height:100vh;margin:0;display:grid;place-items:center;padding:24px;color:var(--ink);font-family:'DM Sans',sans-serif;background:radial-gradient(circle at 0 0,#ffe9f1 0,transparent 33%),radial-gradient(circle at 100% 100%,#fbe1eb 0,transparent 30%),#fcfafb}.card{width:min(100%,440px);background:#fff;border:1px solid var(--line);border-radius:20px;padding:42px;box-shadow:0 20px 55px #8b49631a}.brand{display:flex;align-items:center;gap:11px;margin-bottom:35px;font-family:'Playfair Display',serif;font-size:23px;font-weight:700}.mark{width:38px;height:38px;display:grid;place-items:center;border-radius:12px;color:#fff;background:linear-gradient(145deg,#ef8ab1,#c73071);font-size:27px}.eyebrow{color:var(--pink);font-size:10px;font-weight:700;letter-spacing:1.3px;text-transform:uppercase}h1{margin:7px 0 8px;font-family:'Playfair Display',serif;font-size:30px}.subtitle{margin:0 0 28px;color:var(--muted);font-size:14px;line-height:1.55}label{display:block;margin-bottom:7px;font-size:13px;font-weight:600}input{width:100%;padding:12px 13px;border:1px solid #e7dce1;border-radius:9px;outline:0;font:14px 'DM Sans',sans-serif}input:focus{border-color:#df75a0;box-shadow:0 0 0 3px #fce2ed}button{width:100%;margin-top:22px;border:0;border-radius:9px;padding:13px;background:var(--pink);color:#fff;box-shadow:0 7px 16px #dc4f8733;cursor:pointer;font:600 14px 'DM Sans',sans-serif}.back{display:block;margin-top:21px;text-align:center;color:#a53b68;font-size:13px;font-weight:600;text-decoration:none}.alert{padding:11px 13px;border-radius:9px;font-size:13px;margin-bottom:18px}.success{color:#17745a;background:#e8f8f0;border:1px solid #cef0df}.error{color:#a02d56;background:#fff0f4;border:1px solid #f8d4e0}@media(max-width:480px){body{padding:14px}.card{padding:30px 24px}}
    </style>
</head>
<body><main class="card"><div class="brand"><span class="mark">Y</span><span>Yeral Stecti</span></div><div class="eyebrow">Recuperar acceso</div><h1>¿Olvidaste tu contraseña?</h1><p class="subtitle">Escribe tu correo y te enviaremos un enlace seguro para crear una nueva contraseña.</p>@if(session('status'))<div class="alert success">{{ session('status') }}</div>@endif @if($errors->any())<div class="alert error">{{ $errors->first() }}</div>@endif <form method="POST" action="{{ route('password.email') }}">@csrf <label for="email">Correo electrónico</label><input id="email" name="email" type="email" value="{{ old('email') }}" autocomplete="email" autofocus required><button type="submit">Enviar enlace de recuperación</button></form><a class="back" href="{{ route('login') }}">← Volver a iniciar sesión</a></main></body>
</html>
